spring.application.name=spring-boot-crud-base-task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=task_manager_user
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update